Repository freenas/iocage-ix-plugins, pull requests merged in 2019-10, with the labels that each got.

#176 NAS-103416 / 11.3 / - Move all Plugins to FreeBSD 11.3 jails
  asigra.json
  backuppc.json
  bacula-server.json
  bitcoin-node.json
  bru-server.json
  clamav.json
  couchpotato.json
  deluge.json
  emby.json
  gitlab-runner.json
  gitlab.json
  iconik.json
  jenkins-lts.json
  jenkins.json
  mineos.json
  nextcloud.json
  plexmediaserver-plexpass.json
  plexmediaserver.json
  qbittorrent.json
  radarr.json
  redmine.json
  rslsync.json
  sonarr.json
  subsonic.json
  syncthing.json
  tarsnap.json
  tautulli.json
  transmission.json
  zoneminder.json
Labels: backport-11.3, jira

#181 NAS-103489 / 11.3 / NAT Support / Vnet cleanup
  asigra.json
  bitcoin-node.json
  bru-server.json
  clamav.json
  gitlab.json
  iconik.json
  qbittorrent.json
  tarsnap.json
Labels: backport-11.3, jira

#183 NAS-103450 / 11.3 / Add category keys to all plugins
  INDEX
  asigra-11.1.json
  asigra.json
  backuppc.json
  bacula-server.json
  bitcoin-node.json
  bru-server.json
  clamav.json
  couchpotato.json
  deluge.json
  emby.json
  gitlab-runner.json
  gitlab.json
  iconik.json
  jenkins-lts.json
  jenkins.json
  mineos.json
  nextcloud.json
  plexmediaserver-plexpass.json
  plexmediaserver.json
  qbittorrent.json
  radarr.json
  redmine.json
  rslsync.json
  sonarr.json
  subsonic.json
  syncthing.json
  tarsnap.json
  tautulli.json
  transmission.json
  zoneminder.json
Labels: backport-11.3

#189 NAS-102724 / 11.3 / Add maintainer property
  INDEX
Labels: skip jira status
